// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: gopherlink.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayStatus int32

const (
	PlayStatus_STOPPED PlayStatus = 0
	PlayStatus_PLAYING PlayStatus = 1
	PlayStatus_PAUSED  PlayStatus = 2
)

// Enum value maps for PlayStatus.
var (
	PlayStatus_name = map[int32]string{
		0: "STOPPED",
		1: "PLAYING",
		2: "PAUSED",
	}
	PlayStatus_value = map[string]int32{
		"STOPPED": 0,
		"PLAYING": 1,
		"PAUSED":  2,
	}
)

func (x PlayStatus) Enum() *PlayStatus {
	p := new(PlayStatus)
	*p = x
	return p
}

func (x PlayStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gopherlink_proto_enumTypes[0].Descriptor()
}

func (PlayStatus) Type() protoreflect.EnumType {
	return &file_gopherlink_proto_enumTypes[0]
}

func (x PlayStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayStatus.Descriptor instead.
func (PlayStatus) EnumDescriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{0}
}

type SeekType int32

const (
	SeekType_TO_DURATION     SeekType = 0
	SeekType_ADD_DURATION    SeekType = 1
	SeekType_REMOVE_DURATION SeekType = 2
)

// Enum value maps for SeekType.
var (
	SeekType_name = map[int32]string{
		0: "TO_DURATION",
		1: "ADD_DURATION",
		2: "REMOVE_DURATION",
	}
	SeekType_value = map[string]int32{
		"TO_DURATION":     0,
		"ADD_DURATION":    1,
		"REMOVE_DURATION": 2,
	}
)

func (x SeekType) Enum() *SeekType {
	p := new(SeekType)
	*p = x
	return p
}

func (x SeekType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeekType) Descriptor() protoreflect.EnumDescriptor {
	return file_gopherlink_proto_enumTypes[1].Descriptor()
}

func (SeekType) Type() protoreflect.EnumType {
	return &file_gopherlink_proto_enumTypes[1]
}

func (x SeekType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeekType.Descriptor instead.
func (SeekType) EnumDescriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{1}
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      int64      `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Playing PlayStatus `protobuf:"varint,2,opt,name=playing,proto3,enum=database.PlayStatus" json:"playing,omitempty"`
	Usage   *Usage     `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetOk() int64 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *Status) GetPlaying() PlayStatus {
	if x != nil {
		return x.Playing
	}
	return PlayStatus_STOPPED
}

func (x *Status) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ram float32 `protobuf:"fixed32,1,opt,name=ram,proto3" json:"ram,omitempty"`
	Cpu float32 `protobuf:"fixed32,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
}

func (x *Usage) Reset() {
	*x = Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{1}
}

func (x *Usage) GetRam() float32 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *Usage) GetCpu() float32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

type NowPlayingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  string     `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Playing  PlayStatus `protobuf:"varint,2,opt,name=playing,proto3,enum=database.PlayStatus" json:"playing,omitempty"`
	Duration int64      `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Elapsed  int64      `protobuf:"varint,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
}

func (x *NowPlayingRequest) Reset() {
	*x = NowPlayingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NowPlayingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowPlayingRequest) ProtoMessage() {}

func (x *NowPlayingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowPlayingRequest.ProtoReflect.Descriptor instead.
func (*NowPlayingRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{2}
}

func (x *NowPlayingRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *NowPlayingRequest) GetPlaying() PlayStatus {
	if x != nil {
		return x.Playing
	}
	return PlayStatus_STOPPED
}

func (x *NowPlayingRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *NowPlayingRequest) GetElapsed() int64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

type SeekRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration int64    `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Type     SeekType `protobuf:"varint,2,opt,name=type,proto3,enum=database.SeekType" json:"type,omitempty"`
}

func (x *SeekRequest) Reset() {
	*x = SeekRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekRequest) ProtoMessage() {}

func (x *SeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekRequest.ProtoReflect.Descriptor instead.
func (*SeekRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{3}
}

func (x *SeekRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SeekRequest) GetType() SeekType {
	if x != nil {
		return x.Type
	}
	return SeekType_TO_DURATION
}

type SongInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  string     `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Playing  PlayStatus `protobuf:"varint,2,opt,name=playing,proto3,enum=database.PlayStatus" json:"playing,omitempty"`
	Duration int64      `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Elapsed  int64      `protobuf:"varint,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Author   string     `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Title    string     `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *SongInfo) Reset() {
	*x = SongInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongInfo) ProtoMessage() {}

func (x *SongInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongInfo.ProtoReflect.Descriptor instead.
func (*SongInfo) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{4}
}

func (x *SongInfo) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *SongInfo) GetPlaying() PlayStatus {
	if x != nil {
		return x.Playing
	}
	return PlayStatus_STOPPED
}

func (x *SongInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SongInfo) GetElapsed() int64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *SongInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SongInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SongRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL     string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	GuildId string `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (x *SongRequest) Reset() {
	*x = SongRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongRequest) ProtoMessage() {}

func (x *SongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongRequest.ProtoReflect.Descriptor instead.
func (*SongRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{5}
}

func (x *SongRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *SongRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type SongAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Song *SongRequest `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Info *SongInfo    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SongAdded) Reset() {
	*x = SongAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongAdded) ProtoMessage() {}

func (x *SongAdded) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongAdded.ProtoReflect.Descriptor instead.
func (*SongAdded) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{6}
}

func (x *SongAdded) GetSong() *SongRequest {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *SongAdded) GetInfo() *SongInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type SongRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Song *SongRequest `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Ok   int64        `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *SongRemoved) Reset() {
	*x = SongRemoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongRemoved) ProtoMessage() {}

func (x *SongRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongRemoved.ProtoReflect.Descriptor instead.
func (*SongRemoved) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{7}
}

func (x *SongRemoved) GetSong() *SongRequest {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *SongRemoved) GetOk() int64 {
	if x != nil {
		return x.Ok
	}
	return 0
}

type DiscordVoiceServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	GuildId   string `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Endpoint  string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *DiscordVoiceServer) Reset() {
	*x = DiscordVoiceServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscordVoiceServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordVoiceServer) ProtoMessage() {}

func (x *DiscordVoiceServer) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordVoiceServer.ProtoReflect.Descriptor instead.
func (*DiscordVoiceServer) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{8}
}

func (x *DiscordVoiceServer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DiscordVoiceServer) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *DiscordVoiceServer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiscordVoiceServer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DiscordVoiceServer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string     `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Playing PlayStatus `protobuf:"varint,2,opt,name=playing,proto3,enum=database.PlayStatus" json:"playing,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{9}
}

func (x *Player) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Player) GetPlaying() PlayStatus {
	if x != nil {
		return x.Playing
	}
	return PlayStatus_STOPPED
}

type PlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     int64   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Player *Player `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *PlayerResponse) Reset() {
	*x = PlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResponse) ProtoMessage() {}

func (x *PlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResponse.ProtoReflect.Descriptor instead.
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerResponse) GetOk() int64 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *PlayerResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_gopherlink_proto protoreflect.FileDescriptor

var file_gopherlink_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x6f, 0x6b, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x69, 0x6e, 0x67, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x05, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x72, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x63, 0x70, 0x75, 0x22, 0x94, 0x01, 0x0a, 0x11, 0x4e, 0x6f, 0x77, 0x50,
	0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x22, 0x51,
	0x0a, 0x0b, 0x53, 0x65, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x53, 0x65, 0x65, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0xb9, 0x01, 0x0a, 0x08, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x3a, 0x0a,
	0x0b, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x09, 0x53, 0x6f, 0x6e,
	0x67, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x6e,
	0x67, 0x12, 0x26, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x48, 0x0a, 0x0b, 0x53, 0x6f, 0x6e,
	0x67, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x6f, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x73,
	0x6f, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x6f, 0x6b, 0x22, 0x99, 0x01, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x56,
	0x6f, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x53, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x69, 0x6e, 0x67, 0x22, 0x4a, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x2a, 0x32, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x41, 0x55, 0x53,
	0x45, 0x44, 0x10, 0x02, 0x2a, 0x42, 0x0a, 0x08, 0x53, 0x65, 0x65, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x4f, 0x5f, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x44, 0x44, 0x5f, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x44, 0x55,
	0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x32, 0x84, 0x03, 0x0a, 0x0a, 0x47, 0x6f, 0x70,
	0x68, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x3f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x6f, 0x69, 0x63, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x15, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x53, 0x6f, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x65, 0x64, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0a, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x4e, 0x6f, 0x77,
	0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x4e, 0x6f, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x04, 0x53, 0x65,
	0x65, 0x6b, 0x12, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x65,
	0x65, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61,
	0x6d, 0x61, 0x72, 0x65, 0x64, 0x61, 0x79, 0x6f, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x6c,
	0x69, 0x6e, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gopherlink_proto_rawDescOnce sync.Once
	file_gopherlink_proto_rawDescData = file_gopherlink_proto_rawDesc
)

func file_gopherlink_proto_rawDescGZIP() []byte {
	file_gopherlink_proto_rawDescOnce.Do(func() {
		file_gopherlink_proto_rawDescData = protoimpl.X.CompressGZIP(file_gopherlink_proto_rawDescData)
	})
	return file_gopherlink_proto_rawDescData
}

var file_gopherlink_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gopherlink_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gopherlink_proto_goTypes = []interface{}{
	(PlayStatus)(0),            // 0: database.PlayStatus
	(SeekType)(0),              // 1: database.SeekType
	(*Status)(nil),             // 2: database.Status
	(*Usage)(nil),              // 3: database.Usage
	(*NowPlayingRequest)(nil),  // 4: database.NowPlayingRequest
	(*SeekRequest)(nil),        // 5: database.SeekRequest
	(*SongInfo)(nil),           // 6: database.SongInfo
	(*SongRequest)(nil),        // 7: database.SongRequest
	(*SongAdded)(nil),          // 8: database.SongAdded
	(*SongRemoved)(nil),        // 9: database.SongRemoved
	(*DiscordVoiceServer)(nil), // 10: database.DiscordVoiceServer
	(*Player)(nil),             // 11: database.Player
	(*PlayerResponse)(nil),     // 12: database.PlayerResponse
	(*emptypb.Empty)(nil),      // 13: google.protobuf.Empty
}
var file_gopherlink_proto_depIdxs = []int32{
	0,  // 0: database.Status.playing:type_name -> database.PlayStatus
	3,  // 1: database.Status.usage:type_name -> database.Usage
	0,  // 2: database.NowPlayingRequest.playing:type_name -> database.PlayStatus
	1,  // 3: database.SeekRequest.type:type_name -> database.SeekType
	0,  // 4: database.SongInfo.playing:type_name -> database.PlayStatus
	7,  // 5: database.SongAdded.song:type_name -> database.SongRequest
	6,  // 6: database.SongAdded.info:type_name -> database.SongInfo
	7,  // 7: database.SongRemoved.song:type_name -> database.SongRequest
	0,  // 8: database.Player.playing:type_name -> database.PlayStatus
	11, // 9: database.PlayerResponse.player:type_name -> database.Player
	13, // 10: database.Gopherlink.GetStatusStream:input_type -> google.protobuf.Empty
	10, // 11: database.Gopherlink.CreatePlayer:input_type -> database.DiscordVoiceServer
	7,  // 12: database.Gopherlink.AddSong:input_type -> database.SongRequest
	7,  // 13: database.Gopherlink.RemoveSong:input_type -> database.SongRequest
	4,  // 14: database.Gopherlink.NowPlaying:input_type -> database.NowPlayingRequest
	5,  // 15: database.Gopherlink.Seek:input_type -> database.SeekRequest
	2,  // 16: database.Gopherlink.GetStatusStream:output_type -> database.Status
	12, // 17: database.Gopherlink.CreatePlayer:output_type -> database.PlayerResponse
	8,  // 18: database.Gopherlink.AddSong:output_type -> database.SongAdded
	9,  // 19: database.Gopherlink.RemoveSong:output_type -> database.SongRemoved
	6,  // 20: database.Gopherlink.NowPlaying:output_type -> database.SongInfo
	6,  // 21: database.Gopherlink.Seek:output_type -> database.SongInfo
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_gopherlink_proto_init() }
func file_gopherlink_proto_init() {
	if File_gopherlink_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gopherlink_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NowPlayingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeekRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongRemoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscordVoiceServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gopherlink_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gopherlink_proto_goTypes,
		DependencyIndexes: file_gopherlink_proto_depIdxs,
		EnumInfos:         file_gopherlink_proto_enumTypes,
		MessageInfos:      file_gopherlink_proto_msgTypes,
	}.Build()
	File_gopherlink_proto = out.File
	file_gopherlink_proto_rawDesc = nil
	file_gopherlink_proto_goTypes = nil
	file_gopherlink_proto_depIdxs = nil
}
