// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: gopherlink.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayStatus int32

const (
	PlayStatus_STOPPED PlayStatus = 0
	PlayStatus_PLAYING PlayStatus = 1
	PlayStatus_PAUSED  PlayStatus = 2
)

// Enum value maps for PlayStatus.
var (
	PlayStatus_name = map[int32]string{
		0: "STOPPED",
		1: "PLAYING",
		2: "PAUSED",
	}
	PlayStatus_value = map[string]int32{
		"STOPPED": 0,
		"PLAYING": 1,
		"PAUSED":  2,
	}
)

func (x PlayStatus) Enum() *PlayStatus {
	p := new(PlayStatus)
	*p = x
	return p
}

func (x PlayStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gopherlink_proto_enumTypes[0].Descriptor()
}

func (PlayStatus) Type() protoreflect.EnumType {
	return &file_gopherlink_proto_enumTypes[0]
}

func (x PlayStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayStatus.Descriptor instead.
func (PlayStatus) EnumDescriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{0}
}

type SeekType int32

const (
	SeekType_TO_DURATION     SeekType = 0
	SeekType_ADD_DURATION    SeekType = 1
	SeekType_REMOVE_DURATION SeekType = 2
)

// Enum value maps for SeekType.
var (
	SeekType_name = map[int32]string{
		0: "TO_DURATION",
		1: "ADD_DURATION",
		2: "REMOVE_DURATION",
	}
	SeekType_value = map[string]int32{
		"TO_DURATION":     0,
		"ADD_DURATION":    1,
		"REMOVE_DURATION": 2,
	}
)

func (x SeekType) Enum() *SeekType {
	p := new(SeekType)
	*p = x
	return p
}

func (x SeekType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeekType) Descriptor() protoreflect.EnumDescriptor {
	return file_gopherlink_proto_enumTypes[1].Descriptor()
}

func (SeekType) Type() protoreflect.EnumType {
	return &file_gopherlink_proto_enumTypes[1]
}

func (x SeekType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeekType.Descriptor instead.
func (SeekType) EnumDescriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{1}
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool       `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	GuildId string     `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Playing PlayStatus `protobuf:"varint,3,opt,name=playing,proto3,enum=database.PlayStatus" json:"playing,omitempty"`
	Usage   *Usage     `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Status) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Status) GetPlaying() PlayStatus {
	if x != nil {
		return x.Playing
	}
	return PlayStatus_STOPPED
}

func (x *Status) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ram float32 `protobuf:"fixed32,1,opt,name=ram,proto3" json:"ram,omitempty"`
	Cpu float32 `protobuf:"fixed32,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
}

func (x *Usage) Reset() {
	*x = Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{1}
}

func (x *Usage) GetRam() float32 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *Usage) GetCpu() float32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

type NowPlayingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  string     `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Playing  PlayStatus `protobuf:"varint,2,opt,name=playing,proto3,enum=database.PlayStatus" json:"playing,omitempty"`
	Duration int64      `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Elapsed  int64      `protobuf:"varint,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
}

func (x *NowPlayingRequest) Reset() {
	*x = NowPlayingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NowPlayingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowPlayingRequest) ProtoMessage() {}

func (x *NowPlayingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowPlayingRequest.ProtoReflect.Descriptor instead.
func (*NowPlayingRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{2}
}

func (x *NowPlayingRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *NowPlayingRequest) GetPlaying() PlayStatus {
	if x != nil {
		return x.Playing
	}
	return PlayStatus_STOPPED
}

func (x *NowPlayingRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *NowPlayingRequest) GetElapsed() int64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

type SeekRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  string   `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Duration int64    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Type     SeekType `protobuf:"varint,3,opt,name=type,proto3,enum=database.SeekType" json:"type,omitempty"`
}

func (x *SeekRequest) Reset() {
	*x = SeekRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekRequest) ProtoMessage() {}

func (x *SeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekRequest.ProtoReflect.Descriptor instead.
func (*SeekRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{3}
}

func (x *SeekRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *SeekRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SeekRequest) GetType() SeekType {
	if x != nil {
		return x.Type
	}
	return SeekType_TO_DURATION
}

type SongInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  string     `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Playing  PlayStatus `protobuf:"varint,2,opt,name=playing,proto3,enum=database.PlayStatus" json:"playing,omitempty"`
	Duration int64      `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Elapsed  int64      `protobuf:"varint,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Author   string     `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Title    string     `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	URL      string     `protobuf:"bytes,7,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *SongInfo) Reset() {
	*x = SongInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongInfo) ProtoMessage() {}

func (x *SongInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongInfo.ProtoReflect.Descriptor instead.
func (*SongInfo) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{4}
}

func (x *SongInfo) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *SongInfo) GetPlaying() PlayStatus {
	if x != nil {
		return x.Playing
	}
	return PlayStatus_STOPPED
}

func (x *SongInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SongInfo) GetElapsed() int64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *SongInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SongInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SongInfo) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type SongRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL     string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	GuildId string `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (x *SongRequest) Reset() {
	*x = SongRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongRequest) ProtoMessage() {}

func (x *SongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongRequest.ProtoReflect.Descriptor instead.
func (*SongRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{5}
}

func (x *SongRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *SongRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type SongAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Song *SongRequest `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Info *SongInfo    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SongAdded) Reset() {
	*x = SongAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongAdded) ProtoMessage() {}

func (x *SongAdded) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongAdded.ProtoReflect.Descriptor instead.
func (*SongAdded) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{6}
}

func (x *SongAdded) GetSong() *SongRequest {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *SongAdded) GetInfo() *SongInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type SongPauseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (x *SongPauseRequest) Reset() {
	*x = SongPauseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongPauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongPauseRequest) ProtoMessage() {}

func (x *SongPauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongPauseRequest.ProtoReflect.Descriptor instead.
func (*SongPauseRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{7}
}

func (x *SongPauseRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type SongStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (x *SongStopRequest) Reset() {
	*x = SongStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongStopRequest) ProtoMessage() {}

func (x *SongStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongStopRequest.ProtoReflect.Descriptor instead.
func (*SongStopRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{8}
}

func (x *SongStopRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type SongRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Song *SongInfo `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Ok   bool      `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *SongRemoved) Reset() {
	*x = SongRemoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongRemoved) ProtoMessage() {}

func (x *SongRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongRemoved.ProtoReflect.Descriptor instead.
func (*SongRemoved) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{9}
}

func (x *SongRemoved) GetSong() *SongInfo {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *SongRemoved) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DiscordVoiceServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	GuildId   string `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Endpoint  string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *DiscordVoiceServer) Reset() {
	*x = DiscordVoiceServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscordVoiceServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordVoiceServer) ProtoMessage() {}

func (x *DiscordVoiceServer) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordVoiceServer.ProtoReflect.Descriptor instead.
func (*DiscordVoiceServer) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{10}
}

func (x *DiscordVoiceServer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DiscordVoiceServer) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *DiscordVoiceServer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiscordVoiceServer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DiscordVoiceServer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string     `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Playing PlayStatus `protobuf:"varint,2,opt,name=playing,proto3,enum=database.PlayStatus" json:"playing,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{11}
}

func (x *Player) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Player) GetPlaying() PlayStatus {
	if x != nil {
		return x.Playing
	}
	return PlayStatus_STOPPED
}

type PlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool    `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Player *Player `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *PlayerResponse) Reset() {
	*x = PlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResponse) ProtoMessage() {}

func (x *PlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResponse.ProtoReflect.Descriptor instead.
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PlayerResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type QueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{13}
}

func (x *QueueRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type Queue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string      `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Songs   []*SongInfo `protobuf:"bytes,2,rep,name=songs,proto3" json:"songs,omitempty"`
}

func (x *Queue) Reset() {
	*x = Queue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{14}
}

func (x *Queue) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Queue) GetSongs() []*SongInfo {
	if x != nil {
		return x.Songs
	}
	return nil
}

type VolumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string  `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Volume  float32 `protobuf:"fixed32,2,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *VolumeRequest) Reset() {
	*x = VolumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRequest) ProtoMessage() {}

func (x *VolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRequest.ProtoReflect.Descriptor instead.
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{15}
}

func (x *VolumeRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *VolumeRequest) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type VolumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool    `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Volume float32 `protobuf:"fixed32,2,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *VolumeResponse) Reset() {
	*x = VolumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeResponse) ProtoMessage() {}

func (x *VolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeResponse.ProtoReflect.Descriptor instead.
func (*VolumeResponse) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{16}
}

func (x *VolumeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VolumeResponse) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type LoopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Loop    bool   `protobuf:"varint,2,opt,name=loop,proto3" json:"loop,omitempty"`
}

func (x *LoopRequest) Reset() {
	*x = LoopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopRequest) ProtoMessage() {}

func (x *LoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopRequest.ProtoReflect.Descriptor instead.
func (*LoopRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{17}
}

func (x *LoopRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *LoopRequest) GetLoop() bool {
	if x != nil {
		return x.Loop
	}
	return false
}

type LoopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Loop bool `protobuf:"varint,2,opt,name=loop,proto3" json:"loop,omitempty"`
}

func (x *LoopResponse) Reset() {
	*x = LoopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopResponse) ProtoMessage() {}

func (x *LoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopResponse.ProtoReflect.Descriptor instead.
func (*LoopResponse) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{18}
}

func (x *LoopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoopResponse) GetLoop() bool {
	if x != nil {
		return x.Loop
	}
	return false
}

type SkipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId string `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (x *SkipRequest) Reset() {
	*x = SkipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gopherlink_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipRequest) ProtoMessage() {}

func (x *SkipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopherlink_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipRequest.ProtoReflect.Descriptor instead.
func (*SkipRequest) Descriptor() ([]byte, []int) {
	return file_gopherlink_proto_rawDescGZIP(), []int{19}
}

func (x *SkipRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

var File_gopherlink_proto protoreflect.FileDescriptor

var file_gopherlink_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12,
	0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x12,
	0x25, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x05, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x72, 0x61,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x63, 0x70, 0x75, 0x22, 0x94, 0x01, 0x0a, 0x11, 0x4e, 0x6f, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x22, 0x6c, 0x0a, 0x0b, 0x53, 0x65,
	0x65, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x65, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xcb, 0x01, 0x0a, 0x08, 0x53, 0x6f, 0x6e,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64,
	0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65,
	0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22, 0x3a, 0x0a, 0x0b, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x49, 0x64, 0x22, 0x5e, 0x0a, 0x09, 0x53, 0x6f, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12,
	0x29, 0x0a, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x2d, 0x0a, 0x10, 0x53, 0x6f, 0x6e, 0x67, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x64, 0x22, 0x2c, 0x0a, 0x0f, 0x53, 0x6f, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22,
	0x45, 0x0a, 0x0b, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x26,
	0x0a, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x99, 0x01, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x72, 0x64, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x53, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x22, 0x4a, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x4c,
	0x0a, 0x05, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x49, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x6f, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x73, 0x6f, 0x6e, 0x67, 0x73, 0x22, 0x42, 0x0a, 0x0d,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x22, 0x38, 0x0a, 0x0e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x0b, 0x4c, 0x6f,
	0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x22, 0x32, 0x0a, 0x0c, 0x4c, 0x6f, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6f, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x22, 0x28, 0x0a, 0x0b,
	0x53, 0x6b, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x2a, 0x32, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x50, 0x41, 0x55, 0x53, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x42, 0x0a, 0x08, 0x53, 0x65,
	0x65, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x4f, 0x5f, 0x44, 0x55, 0x52,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x44, 0x44, 0x5f, 0x44,
	0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x4d,
	0x4f, 0x56, 0x45, 0x5f, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x32, 0xe4,
	0x05, 0x0a, 0x0a, 0x47, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x3f, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x48,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1c,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x72,
	0x64, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x18, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x53,
	0x6f, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53,
	0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x65, 0x64, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x09, 0x50, 0x61, 0x75, 0x73, 0x65, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x1a,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x50, 0x61,
	0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x4e, 0x6f, 0x77, 0x50,
	0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x4e, 0x6f, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53,
	0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x16, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x22, 0x00,
	0x12, 0x33, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x6b, 0x12, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12,
	0x17, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x04, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x15, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4c,
	0x6f, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a,
	0x04, 0x53, 0x6b, 0x69, 0x70, 0x12, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x53, 0x6b, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x64, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6d, 0x61, 0x72, 0x65, 0x64, 0x61, 0x79, 0x6f, 0x2f, 0x67,
	0x6f, 0x70, 0x68, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gopherlink_proto_rawDescOnce sync.Once
	file_gopherlink_proto_rawDescData = file_gopherlink_proto_rawDesc
)

func file_gopherlink_proto_rawDescGZIP() []byte {
	file_gopherlink_proto_rawDescOnce.Do(func() {
		file_gopherlink_proto_rawDescData = protoimpl.X.CompressGZIP(file_gopherlink_proto_rawDescData)
	})
	return file_gopherlink_proto_rawDescData
}

var file_gopherlink_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gopherlink_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_gopherlink_proto_goTypes = []interface{}{
	(PlayStatus)(0),            // 0: database.PlayStatus
	(SeekType)(0),              // 1: database.SeekType
	(*Status)(nil),             // 2: database.Status
	(*Usage)(nil),              // 3: database.Usage
	(*NowPlayingRequest)(nil),  // 4: database.NowPlayingRequest
	(*SeekRequest)(nil),        // 5: database.SeekRequest
	(*SongInfo)(nil),           // 6: database.SongInfo
	(*SongRequest)(nil),        // 7: database.SongRequest
	(*SongAdded)(nil),          // 8: database.SongAdded
	(*SongPauseRequest)(nil),   // 9: database.SongPauseRequest
	(*SongStopRequest)(nil),    // 10: database.SongStopRequest
	(*SongRemoved)(nil),        // 11: database.SongRemoved
	(*DiscordVoiceServer)(nil), // 12: database.DiscordVoiceServer
	(*Player)(nil),             // 13: database.Player
	(*PlayerResponse)(nil),     // 14: database.PlayerResponse
	(*QueueRequest)(nil),       // 15: database.QueueRequest
	(*Queue)(nil),              // 16: database.Queue
	(*VolumeRequest)(nil),      // 17: database.VolumeRequest
	(*VolumeResponse)(nil),     // 18: database.VolumeResponse
	(*LoopRequest)(nil),        // 19: database.LoopRequest
	(*LoopResponse)(nil),       // 20: database.LoopResponse
	(*SkipRequest)(nil),        // 21: database.SkipRequest
	(*emptypb.Empty)(nil),      // 22: google.protobuf.Empty
}
var file_gopherlink_proto_depIdxs = []int32{
	0,  // 0: database.Status.playing:type_name -> database.PlayStatus
	3,  // 1: database.Status.usage:type_name -> database.Usage
	0,  // 2: database.NowPlayingRequest.playing:type_name -> database.PlayStatus
	1,  // 3: database.SeekRequest.type:type_name -> database.SeekType
	0,  // 4: database.SongInfo.playing:type_name -> database.PlayStatus
	7,  // 5: database.SongAdded.song:type_name -> database.SongRequest
	6,  // 6: database.SongAdded.info:type_name -> database.SongInfo
	6,  // 7: database.SongRemoved.song:type_name -> database.SongInfo
	0,  // 8: database.Player.playing:type_name -> database.PlayStatus
	13, // 9: database.PlayerResponse.player:type_name -> database.Player
	6,  // 10: database.Queue.songs:type_name -> database.SongInfo
	22, // 11: database.Gopherlink.GetStatusStream:input_type -> google.protobuf.Empty
	12, // 12: database.Gopherlink.CreatePlayer:input_type -> database.DiscordVoiceServer
	7,  // 13: database.Gopherlink.AddSong:input_type -> database.SongRequest
	9,  // 14: database.Gopherlink.PauseSong:input_type -> database.SongPauseRequest
	10, // 15: database.Gopherlink.StopSong:input_type -> database.SongStopRequest
	6,  // 16: database.Gopherlink.RemoveSong:input_type -> database.SongInfo
	4,  // 17: database.Gopherlink.NowPlaying:input_type -> database.NowPlayingRequest
	15, // 18: database.Gopherlink.GetQueue:input_type -> database.QueueRequest
	5,  // 19: database.Gopherlink.Seek:input_type -> database.SeekRequest
	17, // 20: database.Gopherlink.Volume:input_type -> database.VolumeRequest
	19, // 21: database.Gopherlink.Loop:input_type -> database.LoopRequest
	21, // 22: database.Gopherlink.Skip:input_type -> database.SkipRequest
	2,  // 23: database.Gopherlink.GetStatusStream:output_type -> database.Status
	14, // 24: database.Gopherlink.CreatePlayer:output_type -> database.PlayerResponse
	8,  // 25: database.Gopherlink.AddSong:output_type -> database.SongAdded
	6,  // 26: database.Gopherlink.PauseSong:output_type -> database.SongInfo
	6,  // 27: database.Gopherlink.StopSong:output_type -> database.SongInfo
	11, // 28: database.Gopherlink.RemoveSong:output_type -> database.SongRemoved
	6,  // 29: database.Gopherlink.NowPlaying:output_type -> database.SongInfo
	16, // 30: database.Gopherlink.GetQueue:output_type -> database.Queue
	6,  // 31: database.Gopherlink.Seek:output_type -> database.SongInfo
	18, // 32: database.Gopherlink.Volume:output_type -> database.VolumeResponse
	20, // 33: database.Gopherlink.Loop:output_type -> database.LoopResponse
	11, // 34: database.Gopherlink.Skip:output_type -> database.SongRemoved
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gopherlink_proto_init() }
func file_gopherlink_proto_init() {
	if File_gopherlink_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gopherlink_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NowPlayingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeekRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongPauseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongRemoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscordVoiceServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Queue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gopherlink_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gopherlink_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gopherlink_proto_goTypes,
		DependencyIndexes: file_gopherlink_proto_depIdxs,
		EnumInfos:         file_gopherlink_proto_enumTypes,
		MessageInfos:      file_gopherlink_proto_msgTypes,
	}.Build()
	File_gopherlink_proto = out.File
	file_gopherlink_proto_rawDesc = nil
	file_gopherlink_proto_goTypes = nil
	file_gopherlink_proto_depIdxs = nil
}
